### PR TITLE
Add David Beazley to keynote speakers list

### PR DESCRIPTION
**Pull request by astronomersiva**

### CODE REVIEW

**Comment by sayanchowdhury** [comment]
squash the commits?

**Review by bravegnu — APPROVED** [review]

**Comment by bravegnu** [comment]
The current description below the photo, looks odd. Can we take use the content from his Twitter page? 

``````
Author of the Python Essential Reference and Python Cookbook. Creator of SWIG, Curio and PLY. 
``````
I will confirm this with David.

**Comment by bravegnu** [comment]
I just realized that he is put up something similar on the short description. We will probably use the following for now. @astronomersiva Can you please update this?

``````
Author of the Python Essential Reference and Python Cookbook.
``````

**Comment by astronomersiva** [comment]
Updated the text.

**Pull request merged**
