### PR TITLE
Add PyLadies Lunch event

### PR DESCRIPTION
**Pull request by ananyo2012**
Hi all,
Since PyLadies Lunch is a planned event this it will be great if we can add it to the website events section and Let all women attending the Conference before hand about this event. We can also share this in social media to spread the word.

I create a PR updating the same. Please review and let me know if the content needs to be updated. Also can you let me know the Location so that I can update the same.

### CODE REVIEW

**Comment by ananyo2012** [comment]
@sharmi Couldn't add you as a reviewer. Please review this PR.

**Comment by bravegnu** [comment]
@sharmi Please review this and let me know.

**Comment by sharmi** [comment]
Sounds great but can we just add it to the schedule for the first day? That way it will reach everyone easier. In this case, we will have to promote the PyLadies page too.

**Comment by bravegnu** [comment]
@astronomersiva Please review and merge
@sharmi Please plan for a twitter announcement.

**Pull request merged**
