### PR TITLE
Changed sponsor's background to white

### PR DESCRIPTION
**Pull request by anujaagarwal**

### CODE REVIEW

**Comment by astronomersiva** [comment]
@anujaagarwal, the design has alternating backgrounds. To fix this, you'll have to swap the ticket and sponsor sections. Just removing the background will break everything else.

**Comment by bravegnu** [comment]
@anujaagarwal Every push generates mails to everybody on the watch list. So please test you changes locally before publishing them here. Please go through the README to setup you local environment for testing your changes.

**Comment by anujaagarwal** [comment]
So, sorry @bravegnu in future I will take care of it.

**Comment by anujaagarwal** [comment]
I am closing this pull request, opening another pull request with correct changes

**Pull request closed without merging**
