### PR TITLE
Add blog feed

### PR DESCRIPTION
**Pull request by astronomersiva**

### CODE REVIEW

**Comment by astronomersiva** [comment]
@zerothabhishek @bravegnu please take a look at this.

Due to CORS, I am not able to test this in development. This will work only in production which is pretty stupid to be honest. I have two ideas to solve this - Add a proxy using something like now.sh that will send the XML file along with the header(we can probably even do the DOM construction there) or add the headers in the server(which I don't think is immediately possible).

Or...just pay and buy feedly.

**Comment by bravegnu** [comment]
twitter-blog

Sometimes when resizing the window the blog and twitter feed, appear stuck, without spacing between them,

**Comment by bravegnu** [comment]
I don't understand the JS part, and probably don't want to. So otherwise LGTM.

We can have a dummy XML file packaged along with the website, that is used in the preview, and use the real XML file for the actual site.

**Comment by astronomersiva** [comment]
@zerothabhishek please take a look at the JS once...

**Comment by astronomersiva** [comment]
@bravegnu please take a look.

**Comment by bravegnu** [comment]
+1 from me.

**Pull request merged**
