### PR TITLE
Day1 and Day2 Talk schedule is updated in table

### PR DESCRIPTION
**Pull request by gnurenga**
Following changes are done,
* Talk title, link to the talk and Speaker name is updated in schedule

### CODE REVIEW

**Comment by bravegnu** [comment]
- We need to get rid of the box around the talk title.
- The staggered talk during the lunch is in Hall B not in Hall A.
- Time needs to be checked and updated.
   - Closing Address: 6:05 PM to 6:15 PM
   - Day 1: Keynote 2: 5:30 PM to 6:30 PM

**Comment by bravegnu** [comment]
* Change "Sponsor" to "Sponsored Talk"

**Comment by gnurenga** [comment]
> * We need to get rid of the box around the talk title.

Tried commenting `table a` css style but it is removing background in another table. Not sure how to ignore the css to remove the background in the table content without affecting the other table
> * The staggered talk during the lunch is in Hall B not in Hall A.
> * Time needs to be checked and updated.
>   
>   * Closing Address: 6:05 PM to 6:15 PM
>   * Day 1: Keynote 2: 5:30 PM to 6:30 PM

**Comment by astronomersiva** [comment]
Superceded by #174

**Pull request closed without merging**
