### PR TITLE
Enable keynote and sponsors section

### PR DESCRIPTION
**Pull request by astronomersiva**

### CODE REVIEW

**Comment by bravegnu** [comment]
tunnel

There is an extra tunnel on the right, is that expected? Or probably the sponsorship section is missing a grey background?

**Comment by astronomersiva** [comment]
Good catch Vijay, fixed it.

**Comment by bravegnu** [comment]
The z-ordering seems to be off, in the sponsor section. The tunnel appears above the background?

**Comment by astronomersiva** [comment]
Fixed the issue with tunnels...the problem is that one section contains the markup for the tunnel but it is actually getting displayed at the bottom of the next section which is kind of counter-intuitive to figure out. This needs a cleanup to ensure that it doesn't happen when other sections are integrated into the home page.

**Review by bravegnu — APPROVED** [review]

**Pull request merged**
