### PR TITLE
Accessibility fixes

### LINKED ISSUE #70: Make sure that user interface elements, that can receive keyboard focus, are highlighted on focus.
The currently active nav item (Home), Submit A Talk, Submit A Workshop, Download Sponsorship Prospectus etc are not highlighted on focus.

### PR DESCRIPTION
**Pull request by astronomersiva**
Fixes https://github.com/pythonindia/inpycon2019/issues/70, https://github.com/pythonindia/inpycon2019/issues/71, https://github.com/pythonindia/inpycon2019/issues/76, #66,

### CODE REVIEW

**Comment by bravegnu** [comment]
@sharmi Can you please check this?

**Comment by bravegnu** [comment]
My only concern after running this through a few accessibility checkers, is that there is a jump in the heading level from h2 to h4. Now that we are at it, we might want to fixup that as well? See http://wave.webaim.org/report#/https://deploy-preview-83--cranky-borg-621833.netlify.com/2019/

**Comment by bravegnu** [comment]
This can be a bit painful, but there seems to be jumps in the heading See http://wave.webaim.org/report#/https://deploy-preview-83--cranky-borg-621833.netlify.com/2019/ Look for the icon: image

**Comment by astronomersiva** [comment]
@bravegnu, I don't think skipped heading levels are an issue(checked with Chrome's Lighthouse Audits too) but are rather alerts.

We have h1 set for the page header(PyCon India) and h2 set for the sub-headings(keynote speakers, event sponsors, etc.). h3 is set for the headings in the blue band - Conference, Workshops and Dev Sprints. It won't be semantical to use h2 tags for these and use h3 for the main headings.

**Comment by bravegnu** [comment]
OK, let's merge this for now. We will improvise based on feedback.

**Review by bravegnu — APPROVED** [review]

**Pull request merged**
