### PR TITLE
[#38] Fixed navbar alignment

### PR DESCRIPTION
**Pull request by Sayak9495**
Please review the alignment. Do let me know if any changes are required.

### CODE REVIEW

**Comment by astronomersiva** [comment]
Thanks for working on this @Sayak9495! Just one small issue...

Screen Shot 2019-05-19 at 17 30 24

**Comment by Sayak9495** [comment]
Sure, I will fix it and push asap.

**Comment by Sayak9495** [comment]
@astronomersiva Please review the changes. I've also added the code to fix the footer(issue #39 )

**Comment by astronomersiva** [comment]
Thanks @Sayak9495 🍰

**Pull request merged**
