### PR TITLE
Add Jake VanderPlas to Keynote Speakers list

### PR DESCRIPTION
**Pull request by astronomersiva**

### CODE REVIEW

**Comment by bravegnu** [comment]
buttons-stuck

Can you check why the buttons got stuck?

**Comment by astronomersiva** [comment]
This has been fixed @bravegnu. I think you just discovered a bug with the way `flex` is handled. It causes an overflow on the right side of the page when applied through CSS but that doesn't happen when applied inline. Definitely very strange.

**Comment by bravegnu** [comment]
> This has been fixed @bravegnu. I think you just discovered a bug with the way `flex` is handled. It causes an overflow on the right side of the page when applied through CSS but that doesn't happen when applied inline. Definitely very strange.

Oh, OK.

**Comment by bravegnu** [comment]
We can get this merged now.

**Review by bravegnu — APPROVED** [review]

**Pull request merged**
